#!/bin/bash -l

#SBATCH --job-name=MC
#SBATCH --partition=debug
#SBATCH --nodes=2
#SBATCH --time=00:30:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=petercybertron@gmail.com


EXE=/global/homes/y/ypwang/Programs/MonteCarlo/v4/main.x

srun -n 48 $EXE





